capybara-nplus1-fix
Kgomotso196/Blog pull request #8
Opened 2023-10-03 16:31 UTC by Kgomotso196

# PROJECT TO DOs
### IN THIS PROJECT I:
1. Wrote integration tests with Capybara gem.
2. Secured app from n+1 problems.
3. Made sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
4. Made sure that I have used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
5. Made sure that I documented my work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
6. Followed the list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

BEFORE:
![before](https://github.com/Kgomotso196/Blog/assets/74494438/e708856f-e49f-47bf-a451-e0152675685b)
AFTER:
![after](https://github.com/Kgomotso196/Blog/assets/74494438/7c3f131d-a4d2-41fc-a75b-ada417363523)

2023-10-03 18:17 UTC, VICTOR-CHUKWU requested changes
Hi @Kgomotso196  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 18:17 UTC, VICTOR-CHUKWU commented on spec/features/post_index_spec.rb
> +      expect(page).to have_css("img[src*='/assets/default_user.png']")
- [ ] all the places you have similar test of have_css is failing, kindly fix that
![image](https://github.com/Kgomotso196/Blog/assets/66097371/10cd8de9-a0f0-4a3b-acad-53277194c446)

2023-10-03 18:17 UTC, VICTOR-CHUKWU commented on spec/features/post_show_spec.rb
> +end
- [ ] Good job in writing those tests, but you are missing some tests like the test that asserts you can see the username of each commenter and the test that asserts you can see the comment each commentor left. kindly fix that

2023-10-04 06:49 UTC, Kgomotso196 commented on spec/features/post_show_spec.rb
> +end
@VICTOR-CHUKWU Thank you for a constructive feedback.

2023-10-04 06:49 UTC, Kgomotso196 commented on spec/features/post_index_spec.rb
> +      expect(page).to have_css("img[src*='/assets/default_user.png']")
@VICTOR-CHUKWU Thank you for a constructive feedback.

2023-10-04 07:23 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @TEAM 

Your project is complete! Great job for taking time to make the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- capybara well-implemented
- Test well added
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 07:25 UTC, merged